### ISSUE TITLE
Unable to setup local Env

### ISSUE THREAD

**Issue by marknicholas-deriv** [Open-Source-Legal/OpenContracts#134]
Is it possible to update the docs so that its easy to setup everything locally? Thank you

**Comment by JSv4** [comment]
I can streamline it a bit. Definitely check out the quickstart instructions if you didn't see those (there's a couple of steps). I'd like to create some kind of setup script too.

**Comment by marknicholas-deriv** [comment]
I did checkout the quick start instructions but i still keep getting erroros and Its really hard to debug them 😓

**Comment by JSv4** [comment]
Hey, I've tweaked a few things. Still don't have a setup script, but it should be *relatively* straight forward for an app of this complexity. High level steps:

1. Clone the repo
2. Build the compose stack (with `-f local.yml` flag)
3. Copy the sample .env files to `./.envs/.local` and update desired values.
4. `docker compose -f local.yml up`

Should be all you need to do. I made some updates to the frontend env file loading, so make sure you `git pull` the latest and rebuild your container images. 

Paste some logs if you're still having troubles? I can't debug what I can't see :-)
