### ISSUE TITLE
Issue with running new labelset

### ISSUE THREAD

**Issue by zdql** [Open-Source-Legal/OpenContracts#145]
Hi all, I cloned the repo and spun it up using the Docker. 

I had to swap the Huggingface Embeddings to OpenAI Embeddings due to https://github.com/JSv4/OpenContracts/issues/135

I was able to upload documents, but would get a silent GQL error when attempting to create a new label set.

Has anyone had a similar error? 

I have absolutely no configs set differently.

**Comment by JSv4** [comment]
Thanks. Will look into this. Can you provide any logs or any additional info?

**Comment by JSv4** [comment]
Was it this:

![image](https://github.com/JSv4/OpenContracts/assets/5049984/4a7eb174-0cc1-4ac8-9914-48e88a527d77)

**Comment by zdql** [comment]
Yes it was that exact error. I can provide more logs just not right this second

**Comment by JSv4** [comment]
I know what it is, I think. When you created the labelset, did you provide an image? I need to have it provide a default if you don't. It's not clear now that it's required.

**Comment by JSv4** [comment]
I'll put together a PR for this. There are a couple small bugs here and there. Thanks for opening the issue.

**Comment by zdql** [comment]
I was not providing an image, that is likely the issue. I can give that a try!

**Comment by JSv4** [comment]
Hey, quick question @zdql, are you running a Mac? Also trying to figure out #135 at some point. I think it's OSX-related but haven't had time to dig in.
