### ISSUE TITLE
TypeError: requires_system_checks must be a list or tuple.

### ISSUE THREAD

**Issue by rmast** [Open-Source-Legal/OpenContracts#171]
django_1           | INFO 2024-07-28 11:36:19,267 0010_setup_query_permissions 13 124717578827584 Installation of default public access group COMPLETE!
django_1           |  OK
django_1           | Open Contracts allowed hosts: ['django', '127.0.0.1', 'localhost', '0.0.0.0']
django_1           | Traceback (most recent call last):
django_1           |   File "/app/manage.py", line 31, in <module>
django_1           |     execute_from_command_line(sys.argv)
django_1           |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
django_1           |     utility.execute()
django_1           |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
django_1           |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1           |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 275, in fetch_command
django_1           |     klass = load_command_class(app_name, subcommand)
django_1           |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 49, in load_command_class
django_1           |     return module.Command()
django_1           |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 284, in __init__
django_1           |     raise TypeError("requires_system_checks must be a list or tuple.")
django_1           | TypeError: requires_system_checks must be a list or tuple.
opencontracts_django_1 exited with code 1

commit d26b78c0acee8232b0e20d40c76f2afd223c5d04 (HEAD -> main, tag: v2.0.0, origin/main, origin/HEAD)
Merge: 4791f48 25db223
Author: JSIV <5049984+JSv4@users.noreply.github.com>
Date:   Fri Jul 26 22:59:31 2024 -0700

    Merge pull request #170 from JSv4/JSv4/upgrade-django-lts

    Upgrade Django LTS. Finally got the coverage checks to pass!

**Comment by rmast** [comment]
This error does not attract attention on 
commit 4791f481c6cf10975a313b0fd455c05f4ab6eb26 (HEAD)
Merge: 75d5d1c 0aa04ca
Author: JSIV <5049984+JSv4@users.noreply.github.com>
Date:   Mon Jul 22 21:50:00 2024 -0700

    Merge pull request #169 from JSv4/JSv4/long-poll-documents

    Long Poll Documents When Document is Processing

**Comment by JSv4** [comment]
Thanks, @rmast. Yeah must be a syntax change from Django 3.2 to 4.2 that the tests didn't pick up. I'll investigate but just roll back to version before that PR 170 was merged for now. It adds no functionality, just moving to latest LTS.

**Comment by JSv4** [comment]
@rmast, still want to test a few things, but want to give [JSv4/post-2-0-0-fixes](https://github.com/JSv4/OpenContracts/tree/JSv4/post-2-0-0-) a shot?

**Comment by rmast** [comment]
I'm not able to see it working, probably because my local PC is too full. I tried yesterday on an Azure server, but wasn't able to log in, not even with a completely local install running the browser on that server.

The production install has other hurdles, like Auth0 and AWS storage.

I tried to spend effort in that Auth0-configuration, but then found that wouldn't work without AWS-storage in the production setup. There was no inbetween configuration with Auth0 and docker storage. I don't know whether that was configured by configuration or yml docker files.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JSv4** [comment]
Resolved via #172

**Comment by rmast** [comment]
I just ran the local main fullstack version locally on an Azure server and was able to upload a document to the remote browser by switching the snap version of Firefox to the PPA on Ubuntu 22.04. I didn't see above error coming by.
