### ISSUE TITLE
fetching same co-ordinate of multiple label's and screen dark in case of extraction

### ISSUE THREAD

**Issue by nihalgurjar47** [Open-Source-Legal/OpenContracts#95]
issue-1:
Hi @JSv4 I am fetching some issue, like when I uploaded some document in **Opencontract** and extracted the text from the document at a different location, so it's fetching the text but in JSON format with the same coordinates. Please check the screenshot below.
![Screenshot from 2023-03-10 13-13-44](https://user-images.githubusercontent.com/104414738/224267094-03a4c6da-eb30-4a38-987f-d802c42e489a.png)
I obtained **Employer's name, address, and zip code** and **control number** from this document after checking the JSON format that I discovered (see below screen shot). 
![Screenshot from 2023-03-10 13-05-19](https://user-images.githubusercontent.com/104414738/224267923-d6a9d303-ce80-4df9-a143-3f9687614c2e.png)
![Screenshot from 2023-03-10 13-05-48](https://user-images.githubusercontent.com/104414738/224267998-d8239866-bd09-4d28-aa1b-0b7d8b433057.png)
![Screenshot from 2023-03-10 13-07-02](https://user-images.githubusercontent.com/104414738/224268011-2f852b5f-1819-402e-ae68-b007036afc04.png)
**Both JSON format are same.**

issue-2:
one more issue I found when we select the text from the document than the screens are fully dark (see below screen shot).
![Screenshot from 2023-03-10 14-19-59](https://user-images.githubusercontent.com/104414738/224269341-dc3fbd20-36af-4141-aac5-54719e5792b1.png)

issue-3:
Every filed bounding box is empty(See in below screenshot).
![Screenshot from 2023-03-10 16-33-03](https://user-images.githubusercontent.com/104414738/224300186-522e7431-be6c-4973-9720-e443db8eeaee.png)

**Comment by JSv4** [comment]
Sorry, that bounding box field is basically useless. It's a hold-over from before multi-page annotations were possible. The bounding boxes you want to look for now are embedded in the `.json field`. Been meaning to work on the documentation for the annotation format, but it should match this:

https://github.com/JSv4/OpenContracts/blob/bce304a1389739654f0ee98f3c11deef3f9172de/opencontractserver/types/dicts.py#L122

For each page in the annotation, that format matches this:

https://github.com/JSv4/OpenContracts/blob/bce304a1389739654f0ee98f3c11deef3f9172de/opencontractserver/types/dicts.py#L96-L108

Note you can create non-contiguous annotations on the same page and the bounding box for that page will be just large enough to cover **all** included tokens. So, if, for example, you chose a token in the top left and bottom right, the page's bounding box would basically cover the page. There is a bug I need to fix where some of the page 1 tokens from the PAWLS pre_processor have enormous bounding boxes that make it seem like the bounding box covers the page even if you only select a single token. 

And on each page, the bounding box matches:



Also, I noticed a bug in the GraphQL query to fetch and display the annotations. I fixed that last night actually, so you'll want to update to the latest version:

```commandline
git pull
docker-compose -f local.yml build
docker-compose -f local.yml up
```

Note I deleted package-lock.json and am relying solely (and cleanly) on yarn, so you may need to delete your node-modules folder in the frontend subdirectory and then re-run `yarn install` from `frontend`. 

Glad you're using the tool and thanks for the feedback! It's largely been a solo project, so thanks for putting up with me while I get used to supporting other envs.

**Comment by JSv4** [comment]
Let me know if that helps @nihalgurjar47. If so, I can remove that old, unused bounding box field and update the documentation as a fix. Also, quick favor, if you like the project, mind starring it ;-) ?

**Comment by nihalgurjar47** [comment]
> Let me know if that helps @nihalgurjar47. If so, I can remove that old, unused bounding box field and update the documentation as a fix. Also, quick favor, if you like the project, mind starring it ;-) ?

 
Ok, I just want to know the uses of the **Tesseract** and **Pawl** algorithms and how they are working together?
This is my requirement if you share some brief about it.

**Comment by JSv4** [comment]
Sure, take a look at the tesseract pre_processor from the pawls project:

https://github.com/allenai/pawls/blob/57fc217ca8d9f3d84f59156414c43e798a76fee8/cli/pawls/preprocessors/tesseract.py#L95-L103

I use this to generate PAWLS tokens and it was written by Allen AI. It's a Python script that extracts text and its location from a PDF file using OCR (Optical Character Recognition) with the help of the Tesseract library. The output is a list of pages, where each page contains information about the page and its tokens (words). 

Here's what each function in the `tesseract.py` preprocessor does (item 4 is the entry point):

1. **`calculate_image_scale_factor` function:**
   - Calculates the scale factors for width and height to convert image coordinates to PDF coordinates.

2. **`extract_page_tokens` function:**
   - Takes a PDF image, its size, and the language to extract text from it.
   - Uses Tesseract to extract text and its location from the image.
   - Rescales the text locations to match the PDF's size.
   - Returns a list of dictionaries containing token information (text and location).

3. **`parse_annotations` function:**
   - Takes a PDF file path and converts it to images using `pdf2image`.
   - Gets the size of each PDF page using the `get_pdf_pages_and_sizes` function.
   - Loops through each page image, extracts tokens using `extract_page_tokens`, and creates a dictionary containing page information and tokens.
   - Returns a list of dictionaries representing pages and their tokens.

4. **`process_tesseract` function:**
   - Takes a PDF file path, calls the `parse_annotations` function, and returns the annotations (pages and tokens).
